
const fs = require('fs');

// 读取原文件
const content = fs.readFileSync('vocabulary.js', 'utf8');

// 语法解析生成器
const grammarParsers = {
    // 名词解析
    "Maraming tao sa parke.": "【语法解析】1. Maraming: 由marami(很多) + ng组成，修饰名词；2. tao: 名词，人；3. sa parke: 介词短语，在公园；4. 整体结构：Maraming + 名词 + sa + 地点，表示\"某地有很多...\"",
    "Ang bahay ay malaki.": "【语法解析】1. Ang: 定冠词，放在名词前表示特指；2. bahay: 名词，房子；3. ay: 系动词，是；4. malaki: 形容词，大；5. 整体结构：Ang + 名词 + ay + 形容词，表示\"某物是...的\"",
    "Uminom ako ng tubig.": "【语法解析】1. Uminom: um-动词，喝(过去式)；2. ako: 第一人称单数主格，我；3. ng tubig: ng短语，表示动作的对象；4. 整体结构：动词 + ako + ng + 名词，表示\"我...某物\"",
    "Masarap ang pagkain.": "【语法解析】1. Masarap: 形容词，美味的；2. ang pagkain: 名词，食物；3. 整体结构：形容词 + ang + 名词，表示\"某物是...的\"",
    "Malawak ang lupa.": "【语法解析】1. Malawak: 形容词，宽阔的；2. ang lupa: 名词，土地；3. 整体结构：形容词在前强调描述，主语在后",
    "Sariwa ang hangin.": "【语法解析】1. Sariwa: 形容词，新鲜的；2. ang hangin: 名词，空气；3. 整体结构：描述性形容词 + ang + 名词",
    "Mainit ang araw.": "【语法解析】1. Mainit: 形容词，热的；2. ang araw: 名词，太阳；3. 整体结构：表示天气/温度的形容词 + ang + 名词",
    "Maraming bituin sa langit.": "【语法解析】1. Maraming: 很多；2. bituin: 星星；3. sa langit: 在天空；4. sa表示\"在...(地方)\"",
    "Bukas ang buwan.": "【语法解析】1. Bukas: 形容词，明亮的；2. ang buwan: 名词，月亮；3. 整体结构：形容词 + ang + 名词",
    "Umuulan ngayon.": "【语法解析】1. Umuulan: 表示\"下雨\"的动词；2. ngayon: 副词，现在；3. 整体结构：天气动词 + 时间副词",
    "Maganda ang lugar.": "【语法解析】1. Maganda: 形容词，漂亮的；2. ang lugar: 名词，地方；3. 整体结构：表示评价的形容词 + ang + 名词",
    "Ano ang klase mo?": "【语法解析】1. Ano: 疑问代词，什么；2. ang klase: 班级；3. mo: 你的，第二人称所有格；4. 整体结构：Ano + ang + 名词 + mo?，表示\"你的...是什么?\"",
    "Kailangan ko ng pera.": "【语法解析】1. Kailangan: 需要；2. ko: 我(第一人称所有格)；3. ng pera: 钱(ng短语表示对象)；4. 整体结构：Kailangan + ko + ng + 名词，表示\"我需要...\"",
    "Gusto kong matulog sa kama.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng的缩写；3. matulog: 动词，睡觉；4. sa kama: 在床上；5. 整体结构：Gusto + kong + 动词短语，表示\"我想要...\"",
    "Ilagay mo dito sa mesa.": "【语法解析】1. Ilagay: 放置；2. mo: 你(第二人称)；3. dito: 这里；4. sa mesa: 在桌子上；5. 整体结构：动词命令式 + mo + 地点短语",
    "Upuan ang silya.": "【语法解析】1. Upuan: 椅子(名词)；2. ang silya: 椅子；3. 整体结构：名词定义结构，\"...就是...\"",
    "Bukas ang bintana.": "【语法解析】1. Bukas: 开着的(形容词)；2. ang bintana: 窗户；3. 整体结构：表示状态的形容词 + ang + 名词",
    "Isara mo ang pinto.": "【语法解析】1. Isara: 关闭(命令式)；2. mo: 你；3. ang pinto: 门；4. 整体结构：动词命令式 + mo + ang + 名词，表示\"请你...某物\"",
    "I-on mo ang ilaw.": "【语法解析】1. I-on: 打开(外来词)；2. mo: 你；3. ang ilaw: 灯；4. 整体结构：动词短语 + mo + ang + 名词",
    "Tawagan mo ako.": "【语法解析】1. Tawagan: 打电话(命令式)；2. mo: 你；3. ako: 我(宾格)；4. 整体结构：动词命令式 + mo + 宾格代词，表示\"请你...我\"",
    "Gamitin ang kompyuter.": "【语法解析】1. Gamitin: 使用；2. ang kompyuter: 电脑；3. 整体结构：动词命令式 + ang + 名词，表示\"请使用...\"",
    "Manood ng telebisyon.": "【语法解析】1. Manood: 看；2. ng telebisyon: 电视；3. 整体结构：Manood + ng + 名词，表示\"看...\"",
    "Makikinig ng radyo.": "【语法解析】1. Makikinig: 听(将来时)；2. ng radyo: 收音机；3. 整体结构：表示活动的动词 + ng + 名词",
    "I-text mo ako.": "【语法解析】1. I-text: 发短信(外来词)；2. mo: 你；3. ako: 我；4. 整体结构：动词短语 + mo + 宾格代词",
    "Gumamit ng internet.": "【语法解析】1. Gumamit: 使用(过去式)；2. ng internet: 互联网；3. 整体结构：Gumamit + ng + 名词，表示\"使用了...\"",
    "Konekta sa wifi.": "【语法解析】1. Konekta: 连接；2. sa wifi: 连接到wifi；3. 整体结构：动词 + sa + 名词，表示\"连接到...\"",
    "Makikinig ng musika.": "【语法解析】1. Makikinig: 听(将来时)；2. ng musika: 音乐；3. ma-前缀动词结构",
    "Bumasa ng libro.": "【语法解析】1. Bumasa: 读(过去式，um-前缀)；2. ng libro: 书；3. um-动词表示完成的动作",
    "Pumunta sa eskwela.": "【语法解析】1. Pumunta: 去(过去式)；2. sa eskwela: 到学校；3. pumunta + sa + 地点，表示\"去了某地\"",
    "Maganda ang guro.": "【语法解析】1. Maganda: 好的；2. ang guro: 老师；3. 形容词修饰人或事物",
    "Mabait ang estudyante.": "【语法解析】1. Mabait: 友善的；2. ang estudyante: 学生；3. 描述性格的形容词 + ang + 名词",
    "Kumain ako ng kanin.": "【语法解析】1. Kumain: 吃(um-前缀)；2. ako: 我；3. ng kanin: 米饭；4. 动作完成结构",
    "Masarap ang ulam.": "【语法解析】1. Masarap: 美味的；2. ang ulam: 菜；3. 描述食物味道的形容词结构",
    "Kumain ng prutas.": "【语法解析】1. Kumain: 吃；2. ng prutas: 水果；3. 动词 + ng 表示动作对象",
    "Kumain ng gulay.": "【语法解析】1. Kumain: 吃；2. ng gulay: 蔬菜；3. um-动词结构表示动作",
    "Kumain ng karne.": "【语法解析】1. Kumain: 吃；2. ng karne: 肉；3. ng短语表示动作的对象",
    "Kumain ng isda.": "【语法解析】1. Kumain: 吃；2. ng isda: 鱼；3. 过去式动作描述",
    "Kumain ng manok.": "【语法解析】1. Kumain: 吃；2. ng manok: 鸡肉；3. ng表示非特定事物",
    "Uminom ng kape.": "【语法解析】1. Uminom: 喝；2. ng kape: 咖啡；3. um-前缀动词表示动作完成",
    "Uminom ng gatas.": "【语法解析】1. Uminom: 喝；2. ng gatas: 牛奶；3. ng表示动作的对象",
    "Lagyan mo ng asin.": "【语法解析】1. Lagyan: 加...(命令式)；2. mo: 你；3. ng asin: 盐；4. 表示添加的动词结构",
    "Lagyan mo ng asukal.": "【语法解析】1. Lagyan: 添加；2. mo: 你；3. ng asukal: 糖；4. 命令式动词结构",
    "Kumain ng tinapay.": "【语法解析】1. Kumain: 吃；2. ng tinapay: 面包；3. um-动词描述过去动作",
    "Gamitin ang lapis.": "【语法解析】1. Gamitin: 使用(命令式)；2. ang lapis: 铅笔；3. ang表示特指某物",
    "Lagyan mo sa papel.": "【语法解析】1. Lagyan: 写/放；2. mo: 你；3. sa papel: 在纸上；4. sa表示位置",
    "Sumakay ng kotse.": "【语法解析】1. Sumakay: 乘坐；2. ng kotse: 汽车；3. sumakay + ng 表示乘坐某种交通工具",
    "Suutin ang sapatos.": "【语法解析】1. Suutin: 穿(命令式)；2. ang sapatos: 鞋子；3. suutin表示穿戴的动作",
    "Suutin ang damit.": "【语法解析】1. Suutin: 穿(命令式)；2. ang damit: 衣服；3. -in后缀表示命令语气",
    "Maganda ang kaibigan ko.": "【语法解析】1. Maganda: 好的；2. ang kaibigan: 朋友；3. ko: 我的；4. 整体结构：形容词 + ang + 名词 + 所有格代词",
    "Mahal ko ang nanay ko.": "【语法解析】1. Mahal: 爱；2. ko: 我；3. ang nanay: 妈妈；4. 整体结构：Mahal + ko + ang + 名词，表示\"我爱...\"",
    "Mahal ko ang tatay ko.": "【语法解析】1. Mahal: 爱；2. ko: 我；3. ang tatay: 爸爸；4. ko放在句末表示\"我的\"",
    "Lolo ko ang matanda.": "【语法解析】1. Lolo: 爷爷；2. ko: 我的；3. ang matanda: 那位老人；4. 整体结构：名词 + ko + ang + 名词，表示\"那位...是我的...\"",
    "Lola ko ang matanda.": "【语法解析】1. Lola: 奶奶；2. ko: 我的；3. ang matanda: 那位老人；4. 表示归属关系的结构",
    "Magkapatid kami.": "【语法解析】1. Magkapatid: 兄弟姐妹关系；2. kami: 我们(不包括听话者)；3. 整体结构：表示关系的形容词 + kami",
    "Asawa ko siya.": "【语法解析】1. Asawa: 配偶；2. ko: 我的；3. siya: 他/她；4. 整体结构：名词 + ko + siya，表示\"他/她是我的...\"",
    "Anak ko siya.": "【语法解析】1. Anak: 孩子；2. ko: 我的；3. siya: 他/她；4. 表示家庭关系的结构",
    "Gamitin ang kamay.": "【语法解析】1. Gamitin: 使用；2. ang kamay: 手；3. 命令式表示要求使用身体部位",
    "Gamitin ang paa.": "【语法解析】1. Gamitin: 使用；2. ang paa: 脚；3. ang表示特指的身体部位",
    "Sakit ng ulo.": "【语法解析】1. Sakit: 疼；2. ng ulo: 头；3. 整体结构：疼痛形容词 + ng + 身体部位，表示\"...疼\"",
    "Masakit ang mata.": "【语法解析】1. Masakit: 疼的；2. ang mata: 眼睛；3. 整体结构：Masakit + ang + 身体部位",
    "Masakit ang ilong.": "【语法解析】1. Masakit: 疼痛的；2. ang ilong: 鼻子；3. 描述身体不适的结构",
    "Bukas ang bibig.": "【语法解析】1. Bukas: 张开的；2. ang bibig: 嘴巴；3. 表示身体状态的结构",
    "Masakit ang tainga.": "【语法解析】1. Masakit: 疼的；2. ang tainga: 耳朵；3. 描述疼痛的形容词结构",
    "Malaki ang puso.": "【语法解析】1. Malaki: 大的；2. ang puso: 心；3. 比喻用法，表示心胸宽广",
    "Gutom ang tiyan.": "【语法解析】1. Gutom: 饿的；2. ang tiyan: 肚子；3. 整体结构：Gutom + ang + 身体部位，表示\"...饿了\"",
    "Masakit ang balikat.": "【语法解析】1. Masakit: 疼痛的；2. ang balikat: 肩膀；3. 表示身体不适的结构",
    "Malaki ang bundok.": "【语法解析】1. Malaki: 大的；2. ang bundok: 山；3. 描述自然物体的结构",
    "Malawak ang ilog.": "【语法解析】1. Malawak: 宽阔的；2. ang ilog: 河；3. 描述地貌的形容词结构",
    "Malawak ang dagat.": "【语法解析】1. Malawak: 广阔的；2. ang dagat: 海；3. 描述海洋的结构",
    "Malawak ang karagatan.": "【语法解析】1. Malawak: 广阔的；2. ang karagatan: 海洋；3. 描述地理特征",
    "Maganda ang isla.": "【语法解析】1. Maganda: 漂亮的；2. ang isla: 岛屿；3. 评价自然风景的结构",
    "Maganda ang talon.": "【语法解析】1. Maganda: 美丽的；2. ang talon: 瀑布；3. 描述自然景观",
    "Malaki ang burol.": "【语法解析】1. Malaki: 大的；2. ang burol: 小山；3. 简单描述结构",
    "Malawak ang kapatagan.": "【语法解析】1. Malawak: 宽阔的；2. ang kapatagan: 平原；3. 描述地形",
    "Malaki ang gubat.": "【语法解析】1. Malaki: 大的；2. ang gubat: 森林；3. 表示面积的结构",
    "Maliliit ang sapa.": "【语法解析】1. Maliliit: 小的(复数形式)；2. ang sapa: 小溪；3. ma-前缀形容词的复数形式",
    "Pumunta sa parke.": "【语法解析】1. Pumunta: 去；2. sa parke: 公园；3. 表示方向的介词短语",
    "Pumunta sa plaza.": "【语法解析】1. Pumunta: 去(过去式)；2. sa plaza: 广场；3. pumunta + sa + 地点",
    "Pumunta sa ospital.": "【语法解析】1. Pumunta: 去；2. sa ospital: 医院；3. 表示去某地的动作",
    "Pumunta sa barangay.": "【语法解析】1. Pumunta: 去；2. sa barangay: 社区；3. 表示社区的词汇",
    "Malaki ang bayan.": "【语法解析】1. Malaki: 大的；2. ang bayan: 城镇；3. 表示规模的形容词结构",
    "Malaki ang lungsod.": "【语法解析】1. Malaki: 大的；2. ang lungsod: 城市；4. 描述城市规模",
    "Malaki ang probinsiya.": "【语法解析】1. Malaki: 大的；2. ang probinsiya: 省份；3. 行政区域描述",
    "Malaki ang bansa.": "【语法解析】1. Malaki: 大的；2. ang bansa: 国家；3. 描述国家面积",
    "Malawak ang daan.": "【语法解析】1. Malawak: 宽阔的；2. ang daan: 道路；3. 描述道路状况",
    "Isang linggo.": "【语法解析】1. Isang: 一个；2. linggo: 周；3. 表示数量的结构，Isang + 名词",
    "Isang buwan.": "【语法解析】1. Isang: 一个；2. buwan: 月；3. 表示时间长度",
    "Isang taon.": "【语法解析】1. Isang: 一个；2. taon: 年；3. 表示时间单位的结构",
    "Isang minuto.": "【语法解析】1. Isang: 一个；2. minuto: 分钟；3. 表示时长的结构",
    "Isang segundo.": "【语法解析】1. Isang: 一个；2. segundo: 秒；3. 短时间表示法",
    "Magandang umaga.": "【语法解析】1. Magandang: maganda + ng的缩写，好的；2. umaga: 早晨；3. 问候语结构：Magandang + 时间",
    "Magandang hapon.": "【语法解析】1. Magandang: 好的；2. hapon: 下午；3. 下午问候语",
    "Magandang gabi.": "【语法解析】1. Magandang: 好的；2. gabi: 晚上；3. 晚上问候语结构",
    "Pumunta sa opisina.": "【语法解析】1. Pumunta: 去；2. sa opisina: 办公室；3. 表示去工作场所",
    "Galit ang amo.": "【语法解析】1. Galit: 生气的；2. ang amo: 老板；3. 描述情绪的形容词结构",
    "Mabait ang manggagawa.": "【语法解析】1. Mabait: 友善的；2. ang manggagawa: 员工；3. 描述工作关系",
    "Kaibigan ang kapwa-manggagawa.": "【语法解析】1. Kaibigan: 朋友；2. ang kapwa-manggagawa: 同事；3. 描述人际关系的结构",
    "Maasahan ang tagapangasiwa.": "【语法解析】1. Maasahan: 可靠的；2. ang tagapangasiwa: 经理；3. ma-前缀表示可能性",
    "Malaki ang suweldo.": "【语法解析】1. Malaki: 大的；2. ang suweldo: 工资；3. 表示薪资高的说法",
    "Malaki ang bonus.": "【语法解析】1. Malaki: 大的；2. ang bonus: 奖金；3. 外来词使用",
    "Mahalaga ang proyekto.": "【语法解析】1. Mahalaga: 重要的；2. ang proyekto: 项目；3. 表示重要性的结构",
    "Mahirap ang gawain.": "【语法解析】1. Mahirap: 困难的；2. ang gawain: 任务；3. 描述难度的形容词结构",
    "Isulat ang ulat.": "【语法解析】1. Isulat: 写(命令式)；2. ang ulat: 报告；3. -in后缀表示命令语气",
    "Mahal ko ang magulang ko.": "【语法解析】1. Mahal: 爱；2. ko: 我；3. ang magulang: 父母；4. 表示家庭关系的结构",
    "Ate ko siya.": "【语法解析】1. Ate: 姐姐；2. ko: 我的；3. siya: 她；4. 表示家庭称谓的结构",
    "Kuya ko siya.": "【语法解析】1. Kuya: 哥哥；2. ko: 我的；3. siya: 他；4. 表示兄长的称谓",
    "Bunso ako.": "【语法解析】1. Bunso: 最小的；2. ako: 我；3. 整体结构：表示身份的名词 + ako",
    "Tiyo ko siya.": "【语法解析】1. Tiyo: 叔叔；2. ko: 我的；3. siya: 他；4. 家庭称谓结构",
    "Tiya ko siya.": "【语法解析】1. Tiya: 阿姨；2. ko: 我的；3. siya: 她；5. 表示女性长辈称谓",
    "Nobyo ko siya.": "【语法解析】1. Nobyo: 男朋友；2. ko: 我的；3. siya: 他；4. 表示伴侣关系",
    "Nobya ko siya.": "【语法解析】1. Nobya: 女朋友；2. ko: 我的；3. siya: 她；4. 表示恋爱关系的结构",
    "Cute ang sanggol.": "【语法解析】1. Cute: 可爱的(外来词)；2. ang sanggol: 婴儿；3. 外来形容词使用",
    "Apo ko siya.": "【语法解析】1. Apo: 孙子；2. ko: 我的；3. siya: 他；4. 表示隔代关系",
    "Gusto kong magbiyahe.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng；3. magbiyahe: 旅行(mag-动词)；4. Gusto + kong + mag-动词结构",
    "Pumunta sa bakasyon.": "【语法解析】1. Pumunta: 去；2. sa bakasyon: 度假；3. 表示活动的介词短语",
    "Pumunta sa paliparan.": "【语法解析】1. Pumunta: 去；2. sa paliparan: 机场；3. 交通场所表达",
    "Sumakay ng tren.": "【语法解析】1. Sumakay: 乘坐；2. ng tren: 火车；3. 乘坐交通工具的表达",
    "Sumakay ng eroplano.": "【语法解析】1. Sumakay: 乘坐；2. ng eroplano: 飞机；3. um-动词表示乘坐的动作",
    "Sumakay ng barko.": "【语法解析】1. Sumakay: 乘坐；2. ng barko: 船；3. 水上交通方式",
    "Sumakay ng taksi.": "【语法解析】1. Sumakay: 乘坐；2. ng taksi: 出租车；3. 城市交通方式",
    "Sumakay ng bisikleta.": "【语法解析】1. Sumakay: 骑；2. ng bisikleta: 自行车；3. 表示骑行的结构",
    "Sumakay ng dyip.": "【语法解析】1. Sumakay: 乘坐；2. ng dyip: 吉普尼；3. 菲律宾特色交通工具",
    "Pumunta sa resort.": "【语法解析】1. Pumunta: 去；2. sa resort: 度假村；3. 外来词使用",
    "Mahalaga ang kalusugan.": "【语法解析】1. Mahalaga: 重要的；2. ang kalusugan: 健康；3. 表示重要性的结构",
    "Pumunta sa doktor.": "【语法解析】1. Pumunta: 去；2. sa doktor: 看医生；3. 表示目的的介词短语",
    "Pumasok sa ospital.": "【语法解析】1. Pumasok: 进入；2. sa ospital: 医院；3. 表示进入某地的动作",
    "Pumunta sa botika.": "【语法解析】1. Pumunta: 去；2. sa botika: 药房；4. 买药相关表达",
    "Kailangan ng gamot.": "【语法解析】1. Kailangan: 需要；2. ng gamot: 药；3. 表示需求的结构",
    "May lagnat siya.": "【语法解析】1. May: 有；2. lagnat: 发烧；3. siya: 他/她；4. 整体结构：May + 病症 + siya，表示\"他/她有...病\"",
    "May sipon ako.": "【语法解析】1. May: 有；2. sipon: 感冒；3. ako: 我；4. 表示身体状况的结构",
    "Ubo ako.": "【语法解析】1. Ubo: 咳嗽；2. ako: 我；3. 整体结构：病症 + ako，表示\"我...(生病了)\"",
    "Kumain ng almusal.": "【语法解析】1. Kumain: 吃；2. ng almusal: 早餐；3. 三餐表达",
    "Kumain ng tanghalian.": "【语法解析】1. Kumain: 吃；2. ng tanghalian: 午餐；3. 午餐表达法",
    "Kumain ng hapunan.": "【语法解析】1. Kumain: 吃；2. ng hapunan: 晚餐；3. 晚餐表达",
    "Kumain ng merienda.": "【语法解析】1. Kumain: 吃；2. ng merienda: 下午茶；3. 菲律宾特色餐点表达",
    "Masarap ang adobo.": "【语法解析】1. Masarap: 美味的；2. ang adobo: 阿斗波；3. 菲律宾菜名使用",
    "Masarap ang sinigang.": "【语法解析】1. Masarap: 美味的；2. ang sinigang: 酸汤；3. 特色食物描述",
    "Masarap ang lechon.": "【语法解析】1. Masarap: 美味的；2. ang lechon: 烤乳猪；3. 节庆食物表达",
    "Masarap ang lumpia.": "【语法解析】1. Masarap: 美味的；2. ang lumpia: 春卷；3. 中式菲律宾菜",
    "Masarap ang sisig.": "【语法解析】1. Masarap: 美味的；2. ang sisig: 炒猪脸肉；4. 地方特色菜",
    "Masarap ang tinola.": "【语法解析】1. Masarap: 美味的；2. ang tinola: 鸡汤；5. 家常汤品",
    "Masarap ang puto.": "【语法解析】1. Masarap: 美味的；2. ang puto: 米糕；6. 传统点心",
    "Masarap ang kakanin.": "【语法解析】1. Masarap: 美味的；2. ang kakanin: 米制品；7. 传统食品类别",
    "Masarap ang halo-halo.": "【语法解析】1. Masarap: 美味的；2. ang halo-halo: 混合甜品；3. 菲律宾特色甜品",
    "Masarap ang suman.": "【语法解析】1. Masarap: 美味的；2. ang suman: 糯米糕；4. 传统甜点",
    "Masarap ang biko.": "【语法解析】1. Masarap: 美味的；2. ang biko: 椰子糕；5. 特色糕点",
    "Sariwa ang kalamansi.": "【语法解析】1. Sariwa: 新鲜的；2. ang kalamansi: 菲律宾柠檬；6. 菲律宾特色水果",
    "Masarap ang mangga.": "【语法解析】1. Masarap: 美味的；2. ang mangga: 芒果；7. 热带水果描述",
    "Masarap ang saging.": "【语法解析】1. Masarap: 美味的；2. ang saging: 香蕉；8. 常见水果表达",
    "Masarap ang pinya.": "【语法解析】1. Masarap: 美味的；2. ang pinya: 菠萝；9. 热带水果",
    "Masarap ang mansanas.": "【语法解析】1. Masarap: 美味的；2. ang mansanas: 苹果；10. 外来水果词",
    "Masarap ang kaimito.": "【语法解析】1. Masarap: 美味的；2. ang kaimito: 星苹果；11. 特色水果",
    "Masarap ang durian.": "【语法解析】1. Masarap: 美味的；2. ang durian: 榴莲；12. 有争议的水果",
    "Masarap ang langka.": "【语法解析】1. Masarap: 美味的；2. ang langka: 菠萝蜜；13. 大型水果",
    "Masarap ang rambutan.": "【语法解析】1. Masarap: 美味的；2. ang rambutan: 红毛丹；14. 带刺水果",
    "Masarap ang atis.": "【语法解析】1. Masarap: 美味的；2. ang atis: 番荔枝；15. 特色水果",
    "Masarap ang bayabas.": "【语法解析】1. Masarap: 美味的；2. ang bayabas: 番石榴；16. 普通水果",
    "Masarap ang suha.": "【语法解析】1. Masarap: 美味的；2. ang suha: 柚子；17. 大体积水果",
    "Masarap ang ampalaya.": "【语法解析】1. Masarap: 美味的；2. ang ampalaya: 苦瓜；18. 苦味蔬菜",
    "Masarap ang talong.": "【语法解析】1. Masarap: 美味的；2. ang talong: 茄子；19. 紫色蔬菜",
    "Masarap ang sitaw.": "【语法解析】1. Masarap: 美味的；2. ang sitaw: 四季豆；20. 豆类蔬菜",
    "Masarap ang kangkong.": "【语法解析】1. Masarap: 美味的；2. ang kangkong: 空心菜；21. 水上蔬菜",
    "Masarap ang pechay.": "【语法解析】1. Masarap: 美味的；2. ang pechay: 小白菜；22. 绿叶蔬菜",
    "Masarap ang repolyo.": "【语法解析】1. Masarap: 美味的；2. ang repolyo: 卷心菜；23. 圆形蔬菜",
    "Masarap ang patatas.": "【语法解析】1. Masarap: 美味的；2. ang patatas: 土豆；24. 根茎类蔬菜",
    "Masarap ang mais.": "【语法解析】1. Masarap: 美味的；2. ang mais: 玉米；25. 谷物类",
    "Masarap ang kalabasa.": "【语法解析】1. Masarap: 美味的；2. ang kalabasa: 南瓜；26. 黄色蔬菜",
    "Masarap ang sayote.": "【语法解析】1. Masarap: 美味的；2. ang sayote: 佛手瓜；27. 绿色蔬菜",
    "Masarap ang okra.": "【语法解析】1. Masarap: 美味的；2. ang okra: 秋葵；28. 有黏液的蔬菜",
    "Huwag magsigarilyo.": "【语法解析】1. Huwag: 不要；2. magsigarilyo: 吸烟(mag-动词)；3. 禁止语气结构：Huwag + mag-动词",
    "Huwag uminom ng alkohol.": "【语法解析】1. Huwag: 不要；2. uminom: 喝；3. ng alkohol: 酒精；4. 表示禁止的结构",
    "Uminom ng tsaa.": "【语法解析】1. Uminom: 喝；2. ng tsaa: 茶；3. 健康饮品表达",
    "Marami akong sigla.": "【语法解析】1. Marami: 很多；2. akong: ako + ng的缩写；3. sigla: 能量；4. 整体结构：Marami + akong + 名词，表示\"我有很多...\"",
    "May trabaho ako.": "【语法解析】1. May: 有；2. trabaho: 工作；3. ako: 我；4. 表示拥有的结构",
    "Mahal kita.": "【语法解析】1. Mahal: 爱；2. kita: 你(宾语)；3. 整体结构：Mahal + kita，表示\"我爱你\"(浪漫表达)",
    "Marami akong kaalaman.": "【语法解析】1. Marami: 很多；2. akong: ako + ng；3. kaalaman: 知识；4. 表示知识丰富的结构",
    "Maganda ang kultura.": "【语法解析】1. Maganda: 美丽的；2. ang kultura: 文化；3. 抽象名词描述",
    "Mahalaga ang tradisyon.": "【语法解析】1. Mahalaga: 重要的；2. ang tradisyon: 传统；3. 表示重要性的结构",
    "Gusto ko ang panitikan.": "【语法解析】1. Gusto: 喜欢；2. ko: 我；3. ang panitikan: 文学；4. 表达喜好的结构",
    "Maganda ang sining.": "【语法解析】1. Maganda: 美丽的；2. ang sining: 艺术；3. 抽象概念描述",
    "Gusto ko ang sayaw.": "【语法解析】1. Gusto: 喜欢；2. ko: 我；3. ang sayaw: 舞蹈；4. 表达兴趣爱好",
    "Maganda ang larawan.": "【语法解析】1. Maganda: 漂亮的；2. ang larawan: 图片；3. 视觉描述",
    "Basahin ang diyaryo.": "【语法解析】1. Basahin: 读(命令式)；2. ang diyaryo: 报纸；3. 表示媒体消费的动作",
    "Basahin ang magasin.": "【语法解析】1. Basahin: 读；2. ang magasin: 杂志；3. 阅读材料表达",
    "Mahalaga ang medya.": "【语法解析】1. Mahalaga: 重要的；2. ang medya: 媒体；3. 社会机构描述",
    "Basahin ang peryodiko.": "【语法解析】1. Basahin: 读；2. ang peryodiko: 期刊；3. 专业出版物",
    "Alamin ang balita.": "【语法解析】1. Alamin: 了解；2. ang balita: 新闻；3. 获取信息的表达",
    "Kailangan ko ng impormasyon.": "【语法解析】1. Kailangan: 需要；2. ko: 我；3. ng impormasyon: 信息；4. 表示需求的结构",
    "Maganda ang ideya.": "【语法解析】1. Maganda: 好的；2. ang ideya: 想法；3. 评价想法的表达",
    "Gusto kong gumawa ng plano.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng；3. gumawa: 制定；4. ng plano: 计划；5. 表示想要做某事",
    "May layunin ako.": "【语法解析】1. May: 有；2. layunin: 目标；3. ako: 我；4. 表示有目标的结构",
    "Maganda ang resulta.": "【语法解析】1. Maganda: 好的；2. ang resulta: 结果；3. 评价结果的表达",
    "May problema ako.": "【语法解析】1. May: 有；2. problema: 问题；3. ako: 我；4. 表示有困难的结构",
    "Kailangan ng solusyon.": "【语法解析】1. Kailangan: 需要；2. ng solusyon: 解决方案；3. 表示需要解决问题",
    "May pagbabago.": "【语法解析】1. May: 有；2. pagbabago: 变化；3. 抽象名词使用",
    "May pag-unlad.": "【语法解析】1. May: 有；2. pag-unlad: 发展；3. 表示进步的结构",
    "Mahalaga ang kalayaan.": "【语法解析】1. Mahalaga: 重要的；2. ang kalayaan: 自由；3. 抽象价值观表达",
    "Mahalaga ang katarungan.": "【语法解析】1. Mahalaga: 重要的；2. ang katarungan: 正义；4. 社会价值",
    "Mahalaga ang kapayapaan.": "【语法解析】1. Mahalaga: 重要的；2. ang kapayapaan: 和平；5. 重要品质",
    "Mahalaga ang pagkakaisa.": "【语法解析】1. Mahalaga: 重要的；2. ang pagkakaisa: 团结；6. 团队价值观",
    "Bigyan mo ng respeto.": "【语法解析】1. Bigyan: 给予；2. mo: 你；3. ng respeto: 尊重；4. 表示给予的结构",
    "Bigyan mo ng paggalang.": "【语法解析】1. Bigyan: 给予；2. mo: 你；3. ng paggalang: 敬意；4. 表达尊重的动作",
    "Mahalaga ang katapatan.": "【语法解析】1. Mahalaga: 重要的；2. ang katapatan: 诚实；3. 重要品质",
    "Mahalaga ang integridad.": "【语法解析】1. Mahalaga: 重要的；2. ang integridad: 诚信；3. 职业操守",
    "Mahalaga ang karunungan.": "【语法解析】1. Mahalaga: 重要的；2. ang karunungan: 智慧；4. 精神追求",
    "Maganda ang katalinuhan.": "【语法解析】1. Maganda: 好的；2. ang katalinuhan: 聪明；5. 个人特质",
    "Mahalaga ang tibay.": "【语法解析】1. Mahalaga: 重要的；2. ang tibay: 坚强；6. 意志品质",
    "Mahalaga ang tapang.": "【语法解析】1. Mahalaga: 重要的；2. ang tapang: 勇气；7. 性格特征",
    "Mahalaga ang pagtitiyaga.": "【语法解析】1. Mahalaga: 重要的；2. ang pagtitiyaga: 耐心；8. 性格优势",
    "Kailangan ng pagsisikap.": "【语法解析】1. Kailangan: 需要；2. ng pagsisikap: 努力；9. 表示需要付出的结构",
    "Mahalaga ang determinasyon.": "【语法解析】1. Mahalaga: 重要的；2. ang determinasyon: 决心；10. 个人品质",
    "Mahalaga ang optimismo.": "【语法解析】1. Mahalaga: 重要的；2. ang optimismo: 乐观；11. 人生态度",
    "Mahalaga ang kumpyansa.": "【语法解析】1. Mahalaga: 重要的；2. ang kumpyansa: 自信；12. 心理特质",
    "May pag-asa.": "【语法解析】1. May: 有；2. pag-asa: 希望；3. 表示存在希望的结构",
    "Gusto ko ng kaligayahan.": "【语法解析】1. Gusto: 想要；2. ko: 我；3. ng kaligayahan: 幸福；4. 表达愿望",
    "Nararamdaman ko ang kasiyahan.": "【语法解析】1. Nararamdaman: 感受(进行时)；2. ko: 我；3. ang kasiyahan: 快乐；5. 表达情感体验",
    "Nararamdaman ko ang galak.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang galak: 喜悦；6. 表达强烈情感",
    "Nararamdaman ko ang lungkot.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang lungkot: 悲伤；4. 表达负面情绪",
    "Nararamdaman ko ang takot.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang takot: 恐惧；5. 表达恐惧感",
    "Nararamdaman ko ang galit.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang galit: 愤怒；6. 表达生气",
    "Nararamdaman ko ang inis.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang inis: 烦恼；7. 表达烦躁",
    "Nararamdaman ko ang pagkabalisa.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang pagkabalisa: 焦虑；8. 心理状态表达",
    "Nararamdaman ko ang pagod.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang pagod: 疲倦；9. 身体感受表达",
    "Nararamdaman ko ang gutom.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang gutom: 饥饿；10. 生理需求",
    "Nararamdaman ko ang kauhaw.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang kauhaw: 口渴；11. 身体感受",
    "Nararamdaman ko ang antok.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang antok: 困倦；12. 疲劳状态",
    "Nararamdaman ko ang pangangati.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang pangangati: 瘙痒；13. 身体不适",
    "May pamamaga.": "【语法解析】1. May: 有；2. pamamaga: 肿胀；3. 身体状况表达",
    "May pagdurugo.": "【语法解析】1. May: 有；2. pagdurugo: 出血；4. 健康状况",
    "Nararamdaman ko ang kahirapan.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang kahirapan: 困难；5. 困难状态",
    "Nararamdaman ko ang kasaganaan.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang kasaganaan: 富裕；6. 富足状态",
    "Nararamdaman ko ang kaguluhan.": "【语法解析】1. Nararamdaman: 感受；2. ko: 我；3. ang kaguluhan: 混乱；7. 混乱状态",
    "May pagkakaiba.": "【语法解析】1. May: 有；2. pagkakaiba: 差异；3. 表示存在不同",
    "May pagkakapareho.": "【语法解析】1. May: 有；2. pagkakapareho: 相似；4. 表示存在共同之处",
    "May relasyon kami.": "【语法解析】1. May: 有；2. relasyon: 关系；3. kami: 我们；5. 表示关系存在",
    "Mahalaga ang komunikasyon.": "【语法解析】1. Mahalaga: 重要的；2. ang komunikasyon: 沟通；3. 社会技能",
    "Gusto kong makipag-usap.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng；3. makipag-usap: 对话；4. 表示交流愿望",
    "Gusto kong magpresentasyon.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng；3. magpresentasyon: 演示；5. 表达工作意向",
    "May pagpupulong tayo.": "【语法解析】1. May: 有；2. pagpupulong: 会议；3. tayo: 我们；4. 表示活动安排",
    "Mahalaga ang pagsasanay.": "【语法解析】1. Mahalaga: 重要的；2. ang pagsasanay: 练习；3. 学习重要性",
    "Saan ang punta mo?": "【语法解析】1. Saan: 哪里；2. ang punta: 目的地；3. mo: 你的；4. 询问去向的疑问句",
    "Malawak ang kalsada.": "【语法解析】1. Malawak: 宽阔的；2. ang kalsada: 道路；3. 描述道路状况",
    "Bago ang sasakyan.": "【语法解析】1. Bago: 新的；2. ang sasakyan: 车；3. 表示物品新旧状态",
    "Pumunta sa bangko.": "【语法解析】1. Pumunta: 去；2. sa bangko: 银行；3. 表示去金融机构",
    
    // 动词部分
    "Kumain ako ng kanin.": "【语法解析】1. Kumain: um-前缀动词，吃(过去式)；2. ako: 第一人称主格，我；3. ng kanin: 表示动作的对象；4. um-动词表示已完成的动作，um- + 词根表示主动态完成体",
    "Uminom ako ng tubig.": "【语法解析】1. Uminom: um-前缀动词，喝(过去式)；2. ako: 我；3. ng tubig: 水；4. um-用于表示动作的完成，动作已结束",
    "Gusto kong matulog.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng的缩写；3. matulog: 动词，睡觉；4. Gusto + kong + 动词原形，表示\"我想要...\"",
    "Gumising ako nang maaga.": "【语法解析】1. Gumising: um-动词，醒来(过去式)；2. ako: 我；3. nang maaga: 副词短语，早；4. nang用于连接副词短语",
    "Maligo ka na.": "【语法解析】1. Maligo: 动词，洗澡；2. ka: 你(第二人称)；3. na: 已经；4. 整体结构：动词 + ka + na，表示\"你...吧\"(建议语气)",
    "Magbihis ka na.": "【语法解析】1. Magbihis: mag-前缀动词，穿衣服；2. ka: 你；3. na: 已经；4. mag-前缀表示主动进行的动作",
    "Maglinis tayo ng bahay.": "【语法解析】1. Maglinis: mag-动词，打扫；2. tayo: 我们(包括听话者)；3. ng bahay: 房子；4. 整体结构：Mag-动词 + tayo + ng + 名词，表示\"我们一起...吧\"",
    "Magluto tayo ng adobo.": "【语法解析】1. Magluto: mag-动词，烹饪；2. tayo: 我们；3. ng adobo: 阿斗波；4. 表示邀请一起做某事",
    "Maghugas ka ng pinggan.": "【语法解析】1. Maghugas: mag-动词，洗；2. ka: 你；3. ng pinggan: 碗碟；4. 表示命令或建议做某事",
    "Maglakad tayo sa parke.": "【语法解析】1. Maglakad: mag-动词，走路；2. tayo: 我们；3. sa parke: 在公园；4. sa表示地点",
    "Tumakbo siya nang mabilis.": "【语法解析】1. Tumakbo: um-动词，跑(过去式)；2. siya: 他/她；3. nang mabilis: 快地；4. nang连接动词和副词",
    "Pumasok ka na.": "【语法解析】1. Pumasok: um-动词，进入/上班；2. ka: 你；3. na: 已经；4. 表示\"你进去/上班吧\"",
    "Lumabas ka na.": "【语法解析】1. Lumabas: um-动词，出去；2. ka: 你；3. na: 已经；4. 表示\"你出去吧\"",
    "Umupo ka rito.": "【语法解析】1. Umupo: um-动词，坐下；2. ka: 你；3. rito: 这里；4. 表示\"坐这里\"",
    "Tumayo ka na.": "【语法解析】1. Tumayo: um-动词，站起来；2. ka: 你；3. na: 已经；4. 表示\"站起来吧\"",
    "Humiga ka sa kama.": "【语法解析】1. Humiga: um-动词，躺下；2. ka: 你；3. sa kama: 在床上；4. sa表示位置",
    "Magsalita ka sa Tagalog.": "【语法解析】1. Magsalita: mag-动词，说话；2. ka: 你；3. sa Tagalog: 用塔加禄语；5. sa表示使用的语言",
    "Makinig ka sa akin.": "【语法解析】1. Makinig: ma-前缀动词，听；2. ka: 你；3. sa akin: 我；4. ma-前缀表示能够或倾向于做某事",
    "Puwede bang magtanong?": "【语法解析】1. Puwede: 可以；2. bang: 疑问助词；3. magtanong: mag-动词，提问；4. 礼貌询问的结构",
    "Sumagot ka sa tanong.": "【语法解析】1. Sumagot: um-动词，回答；2. ka: 你；3. sa tanong: 问题；4. 表示\"回答问题\"",
    "Magsulat ka ng pangalan.": "【语法解析】1. Magsulat: mag-动词，写；2. ka: 你；3. ng pangalan: 名字；4. 表示\"写下名字\"",
    "Bumasa tayo ng libro.": "【语法解析】1. Bumasa: um-动词，读(过去式)；2. tayo: 我们；3. ng libro: 书；4. um-表示完成的动作",
    "Mag-aral ka nang mabuti.": "【语法解析】1. Mag-aral: mag-动词，学习；2. ka: 你；3. nang mabuti: 好好地；5. 表示\"好好学习\"",
    "Turuan mo ako ng Tagalog.": "【语法解析】1. Turuan: 教(命令式)；2. mo: 你；3. ako: 我；4. ng Tagalog: 塔加禄语；5. 表示\"教我...\"",
    "Bumili ako ng prutas.": "【语法解析】1. Bumili: um-动词，买(过去式)；2. ako: 我；3. ng prutas: 水果；4. 表示\"我买了...\"",
    "Magbenta tayo ng kape.": "【语法解析】1. Magbenta: mag-动词，卖；2. tayo: 我们；3. ng kape: 咖啡；4. 表示\"我们卖...吧\"",
    "Magbayad ka na.": "【语法解析】1. Magbayad: mag-动词，付钱；2. ka: 你；3. na: 已经；4. 表示\"去付钱吧\"",
    "Maghanap ka ng bagong sapatos.": "【语法解析】1. Maghanap: mag-动词，寻找；2. ka: 你；3. ng bagong sapatos: 新鞋子；5. 表示\"找新鞋子\"",
    "Pumili ka ng gusto mo.": "【语法解析】1. Pumili: um-动词，选择；2. ka: 你；3. ng gusto mo: 你喜欢的；4. 表示\"选你喜欢的\"",
    "Saan ka nagtatrabaho?": "【语法解析】1. Saan: 哪里；2. ka: 你；3. nagtatrabaho: mag-动词，工作(进行时)；4. naga-前缀表示进行时",
    "Gumawa ka ng assignment.": "【语法解析】1. Gumawa: um-动词，做；2. ka: 你；3. ng assignment: 作业；4. 表示\"做作业\"",
    "Kailan tayo magsisimula?": "【语法解析】1. Kailan: 什么时候；2. tayo: 我们；3. magsisimula: mag-动词，开始(将来时)；5. magsi-前缀表示将来时",
    "Sana matapos na ito.": "【语法解析】1. Sana: 希望；2. matapos: 动词，完成；3. na: 已经；4. ito: 这；5. 表示\"希望这能完成\"",
    "Matutong magmahal.": "【语法解析】1. Matutong: 学会；2. magmahal: mag-动词，爱；3. 表示\"学会去爱\"",
    "Nagustuhan mo ba ang pagkain?": "【语法解析】1. Nagustuhan: mag-动词，喜欢(过去式)；2. mo: 你；3. ba: 疑问助词；4. ang pagkain: 食物；5. 询问是否喜欢",
    "Huwag kang mag-alala.": "【语法解析】1. Huwag: 不要；2. kang: ka + ng的缩写；3. mag-alala: mag-动词，担心；4. 表示\"别担心\"",
    "Mag-isip ka nang mabuti.": "【语法解析】1. Mag-isip: mag-动词，思考；2. ka: 你；3. nang mabuti: 好好地；5. 表示\"好好想想\"",
    "Naalala ko na siya.": "【语法解析】1. Naalala: ma-动词，想起(过去式)；2. ko: 我；3. na: 已经；4. siya: 他/她；5. 表示\"我想起他了\"",
    "Huwag kang makalimot.": "【语法解析】1. Huwag: 不要；2. kang: ka + ng；3. makalimot: ma-动词，忘记；4. 表示\"别忘记\"",
    "Sumakay tayo ng bus.": "【语法解析】1. Sumakay: um-动词，乘坐；2. tayo: 我们；3. ng bus: 公交车；4. 表示\"我们坐...吧\"",
    "Dito na tayo bumaba.": "【语法解析】1. Dito: 这里；2. na: 已经；3. tayo: 我们；4. bumaba: um-动词，下车；5. 表示\"我们在这里下车\"",
    "Magmaneho ka nang dahan-dahan.": "【语法解析】1. Magmaneho: mag-动词，开车；2. ka: 你；3. nang dahan-dahan: 慢慢地；4. 表示\"慢慢开车\"",
    "Gusto kong bumiyahe.": "【语法解析】1. Gusto: 想要；2. kong: ko + ng；3. bumiyahe: um-动词，旅行；4. 表示\"我想要去旅行\"",
    "Lumiko ka sa kanan.": "【语法解析】1. Lumiko: um-动词，转弯；2. ka: 你；3. sa kanan: 右边；4. 表示\"向右转\"",
    "Tumawid tayo sa kalsada.": "【语法解析】1. Tumawid: um-动词，穿过；2. tayo: 我们；3. sa kalsada: 马路；4. 表示\"我们穿过马路吧\"",
    "Dumating na ang package.": "【语法解析】1. Dumating: um-动词，到达；2. na: 已经；3. ang package: 包裹；4. 表示\"包裹到了\"",
    "Umalis na sila.": "【语法解析】1. Umalis: um-动词，离开；2. na: 已经；3. sila: 他们；4. 表示\"他们已经离开了\"",
    "Bumalik ka rito agad.": "【语法解析】1. Bumalik: um-动词，返回；2. ka: 你；3. rito: 这里；4. agad: 马上；5. 表示\"马上回来这里\"",
    "Sundan mo ako.": "【语法解析】1. Sundan: 跟随(命令式)；2. mo: 你；3. ako: 我；4. -in后缀表示命令语气",
    "Hintayin mo ako rito.": "【语法解析】1. Hintayin: 等待(命令式)；2. mo: 你；3. ako: 我；4. rito: 这里；5. 表示\"在这里等我\"",
    "Mag-book tayo ng hotel.": "【语法解析】1. Mag-book: mag-动词，预订；2. tayo: 我们；3. ng hotel: 酒店；4. 外来词作为动词",
    "Pupunta kami sa Boracay.": "【语法解析】1. Pupunta: pumunta的将来时；2. kami: 我们；3. sa Boracay: 去长滩岛；4. 表示将来的动作",
    "Magpasalamat ka sa kanila.": "【语法解析】1. Magpasalamat: mag-动词，感谢；2. ka: 你；3. sa kanila: 他们；4. 表示\"感谢他们\"",
    "Magpaalam ka muna.": "【语法解析】1. Magpaalam: mag-动词，告别；2. ka: 你；3. muna: 先；4. 表示\"先告别吧\"",
    "Mag-anyaya ka ng kaibigan.": "【语法解析】1. Mag-anyaya: mag-动词，邀请；2. ka: 你；3. ng kaibigan: 朋友；4. 表示\"邀请朋友\"",
    "Tumulong ka sa kanila.": "【语法解析】1. Tumulong: um-动词，帮助；2. ka: 你；3. sa kanila: 他们；4. 表示\"帮助他们\"",
    "Humingi ka ng tawad.": "【语法解析】1. Humingi: um-动词，请求；2. ka: 你；3. ng tawad: 原谅；4. 表示\"请求原谅\"",
    "Magkuwento ka tungkol sa bakasyon.": "【语法解析】1. Magkuwento: mag-动词，讲故事；2. ka: 你；3. tungkol sa: 关于；4. bakasyon: 度假；5. 表示\"讲关于...的事\"",
    "Tumawag ka sa kanya.": "【语法解析】1. Tumawag: um-动词，打电话；2. ka: 你；3. sa kanya: 他/她；4. 表示\"打电话给他\"",
    "Magtext ka lang kung kailangan.": "【语法解析】1. Magtext: mag-动词，发短信；2. ka: 你；3. lang: 就；4. kung kailangan: 如果需要；5. 外来词动词使用",
    "Maglaba ka ng mga damit.": "【语法解析】1. Maglaba: mag-动词，洗衣服；2. ka: 你；3. ng mga damit: 衣服；4. mga表示复数",
    "Magwalis ka sa labas.": "【语法解析】1. Magwalis: mag-动词，扫地；2. ka: 你；3. sa labas: 在外面；4. 表示\"去扫外面\"",
    "Magpunas ka ng mesa.": "【语法解析】1. Magpunas: mag-动词，擦拭；2. ka: 你；3. ng mesa: 桌子；4. 表示\"擦桌子\"",
    "Magsuklay ka ng buhok.": "【语法解析】1. Magsuklay: mag-动词，梳头；2. ka: 你；3. ng buhok: 头发；4. 表示\"梳头发\"",
    "Magpahinga ka muna.": "【语法解析】1. Magpahinga: mag-动词，休息；2. ka: 你；3. muna: 先；4. 表示\"先休息一下\"",
    "Magpraktis ka ng gitara.": "【语法解析】1. Magpraktis: mag-动词，练习；2. ka: 你；3. ng gitara: 吉他；4. 表示\"练习吉他\"",
    "Kailangan nating mag-ensayo.": "【语法解析】1. Kailangan: 需要；2. nating: natin + ng；3. mag-ensayo: mag-动词，排练；4. 表示\"我们需要排练\"",
    "Magplano tayo para sa holiday.": "【语法解析】1. Magplano: mag-动词，计划；2. tayo: 我们；3. para sa: 为了；4. holiday: 假期；5. 外来词使用",
    "Mahirap magdesisyon.": "【语法解析】1. Mahirap: 困难的；2. magdesisyon: mag-动词，决定；3. 表示\"很难做决定\"",
    "Sumubok ka ulit.": "【语法解析】1. Sumubok: um-动词，尝试；2. ka: 你；3. ulit: 再一次；4. 表示\"再试一次\"",
    "Ayos lang magkamali.": "【语法解析】1. Ayos lang: 没关系；2. magkamali: mag-动词，犯错；3. 表示\"犯错没关系\"",
    "Umunlad na ang bansa.": "【语法解析】1. Umunlad: um-动词，发展(过去式)；2. na: 已经；3. ang bansa: 国家；4. 表示\"国家发展了\"",
    "Maniwala ka sa akin.": "【语法解析】1. Maniwala: ma-动词，相信；2. ka: 你；3. sa akin: 我；4. 表示\"相信我\"",
    "Naintindihan mo ba?": "【语法解析】1. Naintindihan: ma-动词，理解(过去式)；2. mo: 你；3. ba: 疑问助词；4. 表示\"你理解了吗?\"",
    "Ipaliwanag mo ito sa akin.": "【语法解析】1. Ipaliwanag: 解释(命令式)；2. mo: 你；3. ito: 这；4. sa akin: 我；5. 表示\"跟我解释一下这个\"",
    "Kailangang nating mag-usap.": "【语法解析】1. Kailangang: Kailangan + ng的缩写；2. nating: natin + ng；3. mag-usap: mag-动词，交谈；4. 表示\"我们需要谈谈\"",
    "Magsabi ka ng totoo.": "【语法解析】1. Magsabi: mag-动词，说；2. ka: 你；3. ng totoo: 真话；4. 表示\"说实话\"",
    "Magbigay ka ng tulong.": "【语法解析】1. Magbigay: mag-动词，给予；2. ka: 你；